SELECT * FROM EMPLOYEES;

-- Q1. Display each employee along with the average salary of their department
SELECT EMP_NAME, DEPARTMENT, SALARY,
(AVG(SALARY) OVER (PARTITION BY DEPARTMENT))::NUMERIC(20, 0) AS AVG_SALARY
FROM EMPLOYEES;

-- Q2. For each employee, show: emp_name, department, salary, rank of salary within their department
SELECT EMP_NAME, DEPARTMENT, SALARY,
RANK() OVER (PARTITION BY DEPARTMENT ORDER BY SALARY) AS RANK_
FROM EMPLOYEES;

-- Q3. Show employees whose salary is higher than the department average.
SELECT e.EMP_NAME, e.DEPARTMENT, e.SALARY, 
( SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT = e.DEPARTMENT )::NUMERIC(20, 0) AS AVG_SALARY
FROM EMPLOYEES as e
WHERE e.SALARY > (
	SELECT AVG(SALARY)
	FROM EMPLOYEES
	WHERE DEPARTMENT = e.DEPARTMENT
);

-- USING WINDOW FUNCTION
SELECT E.EMP_NAME, E.DEPARTMENT, E.SALARY, 
(AVG(E.SALARY) OVER (PARTITION BY DEPARTMENT))::NUMERIC(20, 0) AS AVG_SALARY
FROM EMPLOYEES AS E
WHERE E.SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT = E.DEPARTMENT );

-- Q4. Display each employee and the total salary paid in their department.
SELECT E.EMP_NAME, E.DEPARTMENT, E.SALARY, 
(SUM(E.SALARY) OVER (PARTITION BY DEPARTMENT))::NUMERIC(20, 0) AS TOTOL_DEPARTMENT_SALARY
FROM EMPLOYEES AS E;

-- Q5. Find the highest paid employee in each department using window functions.
SELECT E.EMP_NAME, E.DEPARTMENT, E.SALARY
FROM EMPLOYEES AS E
WHERE E.SALARY = (
	SELECT MAX(SALARY) FROM EMPLOYEES
	WHERE DEPARTMENT = E.DEPARTMENT
	GROUP BY DEPARTMENT 
);

SELECT EMP_NAME, DEPARTMENT, SALARY FROM
(SELECT EMP_NAME, DEPARTMENT, SALARY,
 RANK() OVER (PARTITION BY DEPARTMENT ORDER BY SALARY) AS r
 FROM EMPLOYEES)
WHERE r=1;


-- Q6. Find employees who earn more than the average salary of all employees.
SELECT E.EMP_NAME, E.DEPARTMENT, E.SALARY
FROM EMPLOYEES AS E
WHERE E.SALARY > (
	SELECT AVG(SALARY) FROM EMPLOYEES
);

-- Q7. Find employees who earn more than the average salary of their own department.
SELECT E.EMP_NAME, E.DEPARTMENT, E.SALARY
FROM EMPLOYEES AS E
WHERE E.SALARY > (
	SELECT AVG(SALARY) FROM EMPLOYEES
	-- GROUP BY E.DEPARTMENT
	WHERE E.DEPARTMENT = DEPARTMENT
);

-- Q8. Display employees who were hired before the average hire date of their department.
-- I dont know how to find the average date

-- Q9. Find employees whose salary is the maximum in their department using a subquery (NO window functions allowed).
SELECT E.EMP_NAME, E.DEPARTMENT, E.SALARY
FROM EMPLOYEES AS E
WHERE E.SALARY = (
	SELECT MAX(SALARY) FROM EMPLOYEES
	WHERE E.DEPARTMENT = DEPARTMENT
);




